# Generated by Django 3.1.7 on 2021-03-03 08:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='startDay',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 8, 13, 10, 290539, tzinfo=utc), verbose_name='終了'),
        ),
    ]
