# Generated by Django 3.1.7 on 2021-03-03 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_auto_20210303_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarmodel',
            name='cal_data',
            field=models.JSONField(blank=True, null=True, verbose_name='JSONデータ'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='startDay',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 8, 51, 50, 163744, tzinfo=utc), verbose_name='終了'),
        ),
    ]
