# Generated by Django 3.1.7 on 2021-03-03 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20210303_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='endDay',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 8, 56, 17, 458309, tzinfo=utc), verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='startDay',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 8, 56, 17, 458281, tzinfo=utc), verbose_name='開始'),
        ),
    ]
