# Generated by Django 3.1.7 on 2021-03-03 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_auto_20210303_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='allday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='endDay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='startDay',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 13, 6, 17, 659908, tzinfo=utc), verbose_name='開始'),
        ),
    ]
